### ISSUE TITLE
Round-trip conversion between rfc and nim stdlib dates.

### ISSUE THREAD

**Issue by Skrylar** [Skrylar/rfc3339#8]
Because #7 pointed out people want to parse RFC dates and then ultimately get nim date objects, there should be a best-effort converter between the two types.

**Comment by JohnAD** [comment]
I'm happy to help with this also. As I said on the other issue, I'm not a time expert, but willing to test, code, and debug. And write documentation.

BTW, because the web framework I'm writing has macros that recursively convert to/from the following formats:

* JSON Objects
* Simple objects of RootObj
* MongoDB BSON Objects
* templating engine Context Objects
* HTTP request headers

This pretty much means that the Nim Standard `times` library `DateTime` object is not usable. Without getting into details, the following is an error `var a = DateTime()`. For the macros, that breaks things in a lot of subtle ways. So, I've forced the framework to only allow `Time` objects. (Which kid of sucks since I can't store or use dates prior to 1970.)
